feat: improve node mgmt
axelarnetwork/axelar-docs pull request #109
Opened 2022-07-06 12:51 UTC by kalidax

- https://github.com/axelarnetwork/axelar-docs/compare/feat/basic-node-mgmt?expand=1#diff-6f7f43619d794516f84121153f5aab9894480ae1c25c9d1760e02876f64adf4aR19
I added "&" at the end of the command to have the command running in the background, if we don't add it we are stuck until we kill the process.  We also can add [nohup](https://linuxhint.com/how_to_use_nohup_linux/) command at the beginning of the line but it seems it does not work well on Mac.

- Regarding the "axelard status" command, the output is not user friendly. We can use a command like : 
curl -s localhost:26657/status | jq '.result.sync_info' | grep '"catching_up": true' > /dev/null 2>&1 && echo "Node is catching up" || echo "Node is not catching up"
It will directly print the result to the user (we should add curl and jq as prerequites). Makes sense ?

- https://github.com/axelarnetwork/axelar-docs/compare/feat/basic-node-mgmt?expand=1#diff-6f7f43619d794516f84121153f5aab9894480ae1c25c9d1760e02876f64adf4aR78
I added a timestamp to the backup because it is usually considered as a best practice.

2022-07-08 19:19 UTC, talalashraf requested changes

2022-07-08 19:19 UTC, talalashraf commented on pages/node/basic.md
> +ps aux | grep "axelar start"
axelard

2022-07-10 18:13 UTC, kalidax commented on pages/node/basic.md
> +ps aux | grep "axelar start"
fixed

2022-07-21 18:50 UTC, talalashraf approved these changes

2022-07-22 03:56 UTC, merged