fix: bump axelar-core version to v1.0.2
axelarnetwork/axelar-docs pull request #1138
Opened 2024-09-04 15:45 UTC by ffe9f8

2024-09-04 15:47 UTC, StephenFluin requested changes
`vald` is the same binary and should be updated to the same version

2024-09-04 16:52 UTC, milapsheth commented on src/pages/resources/contract-addresses/mainnet.mdx
>  | `vald` version        | `v0.35.5` |
Vald should be changed

2024-09-04 17:34 UTC, StephenFluin commented
Check for other outdated references like this one: https://docs.axelar.dev/dev/amplifier/chain-integration/integrate-a-chain/

2024-09-04 22:57 UTC, StephenFluin requested changes
Still missing pages like https://docs.axelar.dev/dev/amplifier/chain-integration/integrate-a-chain/

2024-09-04 22:57 UTC, StephenFluin commented on src/pages/validator/setup/manual.mdx
> +AXELARD_RELEASE=v0.35.5
This should be 1.0.2 as well.

2024-09-06 17:53 UTC, StephenFluin requested changes
This now specifies an incorrect version of tofnd.

I believe tofnd is still 1.0.1.

2024-09-10 14:31 UTC, StephenFluin approved these changes

2024-09-10 14:32 UTC, merged