feat: add dev blog tutorials
axelarnetwork/axelar-docs pull request #1232
Opened 2024-10-23 17:44 UTC by Olanetsoft

2024-11-01 11:24 UTC, StephenFluin requested changes

2024-11-01 11:24 UTC, StephenFluin commented on src/layouts/navigation.ts
> +import { title } from "process";
I think this was an auto-import from your IDE that we don't want?

2024-11-01 11:24 UTC, StephenFluin commented on src/layouts/navigation.ts
> +          title: "Tutorials",
You are removing the Indexers from the navigation, which I agree with (see #1203 ), but this should be a separate action as the content should be cleaned up as well.

2024-11-01 22:40 UTC, StephenFluin commented
@Olanetsoft Did something happen to this PR? It looks like it includes a bunch of other changes now?

2024-11-02 02:41 UTC, Olanetsoft commented
> Fixes #1225

I think I broke something while I was trying to rebase. I will close this now.

I have sent a new PR [here](https://github.com/axelarnetwork/axelar-docs/pull/1236)

2024-11-02 02:41 UTC, closed without merging