feat: add keplr button
axelarnetwork/axelar-docs pull request #146
Opened 2022-08-03 22:39 UTC by canhtrinh

2022-08-10 13:42 UTC, npty commented
lgtm

2022-08-10 13:58 UTC, npty requested changes
Moved our discussion in slack to here for reference.

**Things to fix:**
1. Content overlap footer

![image](https://user-images.githubusercontent.com/78221556/183919635-f60b189d-0eb5-40e6-a1dd-f357662a2f9b.png)

2. Initial value for adding custom network e.g.
```
{
  "rpc": "YOUR_RPC",
  ...
}

3. A bit of padding at the bottom, so there is a bit of space between the content body and the footer
```

2022-08-25 22:03 UTC, canhtrinh commented
@npty belatedly updating. if good, can u merge directly? thanks!

2022-08-26 14:24 UTC, npty approved these changes

2022-08-26 14:24 UTC, merged