fix: send token example
axelarnetwork/axelar-docs pull request #439
Opened 2023-06-02 22:36 UTC by milapsheth

2023-06-10 10:40 UTC, StephenFluin requested changes

2023-06-10 10:40 UTC, StephenFluin commented on pages/dev/send-tokens/overview.mdx
> +Find a list of assets, their names and their addresses: [Mainnet](../reference/mainnet-contract-addresses) | [Testnet](../reference/testnet-contract-addresses). Note that for the same asset denom,
all of this content should be on one line

2023-06-10 10:40 UTC, StephenFluin commented on pages/dev/send-tokens/overview.mdx
> +For e.g., `USDC` on Ethereum is linked to `axlUSDC` on Avalanche.
The correct english format  for eg is to use this as a parenthetical statement attached to the previous statement.
"the ERC20 symbol could be different on different chains (e.g. USDC on ethereum..."
or you could just use words in your separate sentence.
"For example, `USDC` on ethereum is linked..."

2023-06-10 10:40 UTC, StephenFluin commented on pages/dev/send-tokens/overview.mdx
> +    "axlUSDC", // asset symbol, can be differ by chain, see above.
remove period at the end

2023-06-19 01:20 UTC, milapsheth commented on pages/dev/send-tokens/overview.mdx
> +For e.g., `USDC` on Ethereum is linked to `axlUSDC` on Avalanche.
```suggestion
Find a list of assets, their names and their addresses: [Mainnet](../reference/mainnet-contract-addresses) | [Testnet](../reference/testnet-contract-addresses). Note that for the same asset denom, the ERC20 symbol could be different on different chains (e.g. `USDC` on Ethereum is linked to `axlUSDC` on Avalanche).
```

2023-06-19 01:20 UTC, milapsheth commented on pages/dev/send-tokens/overview.mdx
> +    "axlUSDC", // asset symbol, can be differ by chain, see above.
```suggestion
    "axlUSDC", // asset symbol, can be differ by chain, see above
```

2023-06-19 01:20 UTC, merged