fix: improve its documentation page
axelarnetwork/axelar-docs pull request #600
Opened 2023-10-23 14:15 UTC by Olanetsoft

Revamp the ITS page

- [x] Fixed inconsistent hyperlinks/style formats 
- [x] Navigation update with Card-like option for ITS features
![Screenshot 2023-10-23 at 15 09 16](https://github.com/axelarnetwork/axelar-docs/assets/45847909/0eb6cbf0-09d9-4645-8505-d86c497bbd36)
- [x] Create a new interchain token
![new-token](https://github.com/axelarnetwork/axelar-docs/assets/45847909/abde14b5-939d-448b-b572-f09001f4e1a6)
- [x] Upgrade existing token
![existing token](https://github.com/axelarnetwork/axelar-docs/assets/45847909/4e94b798-0250-4050-bfab-be341c3caf64)
- [ ] Providing complete examples of deploying interchain token service end-to-end

2023-12-11 10:58 UTC, Foivos commented on src/pages/dev/send-tokens/interchain-tokens/intro.astro
> +const title = "What is Interchain Tokens?";
"What are Interchain Tokens?"

2023-12-11 10:58 UTC, Foivos commented on src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
> +Furthermore, your token is categorized as a [Interchain Token](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/interfaces/IInterchainTokenStandard.sol). This classificat
I would prefer something like "Furthermore, your token follows the [Interchain Token Standard]. This means that users can call the `interchainTransfer` method on the token itself to transfer between blockchains.

2023-12-11 10:58 UTC, Foivos commented on src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
> +To create a new Interchain Token:
The steps below describe how to deploy an InterchainToken, not a custom token. To deploy a custom token the user needs to
- deploy their custom ERC20, which should include mint/burn implementations
- use `deployTokenManager` with the correct params (mint/burn as the type) on the ITS
- make sure that the service can call mint/burn on the token.
- Do the same on any other chains the user wants to have their token exist at, using the same deployer address and salt.

2023-12-11 10:58 UTC, Foivos commented on src/pages/dev/send-tokens/interchain-tokens/upgrade-tokens.mdx
> +## Link deployed tokens on multiple chains into Interchain Token(s)
This is what custom tokens do indeed, with regards to the previous comment.

2023-12-18 19:56 UTC, StephenFluin requested changes
Please remove the _meta file you created, please remove the `-old` file you created

2023-12-19 17:17 UTC, ffe9f8 approved these changes

2023-12-21 16:21 UTC, StephenFluin approved these changes

2023-12-21 16:22 UTC, merged