fix: add Gas Service naming convention
axelarnetwork/axelar-docs pull request #715
Opened 2024-01-19 15:35 UTC by ffe9f8

2024-01-19 16:22 UTC, StephenFluin requested changes
I would like us to be prescriptive here about when we talk about relayers, executor, and gas service. We could consider relayers to be an implementation of the gas service, we could look at the gas service as a feature of the relayers, we could call the realyers the executor service. We should figure out what we want and then be clear and consistent everywhere. Talk to @canhtrinh to get thoughts as well.

2024-01-23 20:13 UTC, Olanetsoft approved these changes

2024-01-25 15:06 UTC, StephenFluin commented
> I would like us to be prescriptive here about when we talk about relayers, executor, and gas service. We could consider relayers to be an implementation of the gas service, we could look at the gas service as a feature of the relayers, we could call the realyers the executor service. We should figure out what we want and then be clear and consistent everywhere. Talk to @canhtrinh to get thoughts as well.

I haven't seen any changes here @ffe9f8 ? Is the plan to do this in another PR?

2024-02-01 16:47 UTC, ffe9f8 commented
> > > I would like us to be prescriptive here about when we talk about relayers, executor, and gas service. We could consider relayers to be an implementation of the gas service, we could look at the gas service as a feature of the relayers, we could call the realyers the executor service. We should figure out what we want and then be clear and consistent everywhere. Talk to @canhtrinh to get thoughts as well.
> > 
> > 
> > I haven't seen any changes here @ffe9f8 ? Is the plan to do this in another PR?
> 
> Have a meeting with @canhtrinh tomorrow to discuss Gas Services docs and naming.

Decisions:
- Talk about relayers as separate from Gas Service (working on an EVM relayer documentation set)
- Removed references to "Executor service" from docs for now, talk about them as relayers instead.

cc @canhtrinh

2024-02-01 16:55 UTC, Olanetsoft approved these changes

2024-03-25 09:22 UTC, StephenFluin approved these changes

2024-03-25 09:22 UTC, merged