Inbound Transaction Verification
axelarnetwork/axelar-docs pull request #785
Opened 2024-02-20 19:51 UTC by benjamin852

1. Added docs for evm + cosmos gmp tx verification
2. Added warning for sending txs sent to axelar chain (which we do not yet support)

@milapsheth if you have time feel free to review the cosmos gmp verification to ensure it's accurate. Thanks

2024-02-22 18:03 UTC, benjamin852 commented
> @benjamin852 can you be clear with the state of this PR? I saw code pushed, but is it finished, are all comments addressed? Any desired eng reviews complete?

I don't see any comments here that need to be addressed?
PR is ready to be merged. 
Would be nice to get someone from eng to review the cosmos section here but don't think the whole pr needs to be blocked until then, we could just iterate on it after if someone wants me to change something there.

2024-02-23 18:02 UTC, StephenFluin requested changes

2024-02-24 23:23 UTC, benjamin852 commented on src/pages/dev/general-message-passing/overview.mdx
> +  **NOTE:** GMP Transactions using `callContractWithToken` sent to the Axelar chain itself are not yet supported. Axelar only supports GMP call without token from Axelar to chain X. Transactions sent
It's a feature the team wants to add

2024-02-28 13:26 UTC, StephenFluin approved these changes

2024-02-28 15:14 UTC, merged