fix: rewrite Create a New Interchain Token page
axelarnetwork/axelar-docs pull request #902
Opened 2024-04-03 17:57 UTC by ffe9f8

- Re-write content on https://docs.axelar.dev/dev/send-tokens/interchain-tokens/create-token
- Incorporate glossary link changes from [PR 893](https://github.com/axelarnetwork/axelar-docs/pull/893)

Preview:

2024-04-08 21:26 UTC, Olanetsoft requested changes

2024-04-08 21:26 UTC, Olanetsoft commented on src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
> +  We're making some improvements to the custom token manager flow, which requires temporarily
Can we remove this callout? it's now fixed and tested.

2024-04-08 21:26 UTC, Olanetsoft commented on src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
> -To create the `params` that will be used to initialize the Token Manager in the `deployTokenManager` method above, you can use the [Online Ethereum ABI Encoder](https://adibas03.github.io/online-ethe
This was removed entirely and is not referenced anywhere. can we add it somewhere so developers knows what to do when creating `params`

2024-04-09 12:29 UTC, Olanetsoft requested changes

2024-04-09 17:35 UTC, ffe9f8 commented on src/pages/dev/send-tokens/interchain-tokens/create-token.mdx
> +  * If the `minter` parameter consists of empty bytes when you deployed your token, deploy a [Mint/Burn](/dev/send-tokens/glossary#mintburn) [token manager](/dev/send-tokens/glossary#token-manager) f
Got it. Moved the callout back to its original place.

2024-04-11 21:58 UTC, Olanetsoft approved these changes

2024-04-12 17:43 UTC, merged