fix: add instantiation params to Amplifier contract docs
axelarnetwork/axelar-docs pull request #946
Opened 2024-04-26 20:47 UTC by ffe9f8

- Add instantiation params to Amplifier contract docs
- Re-word chain introduction intro

2024-05-01 16:50 UTC, StephenFluin requested changes

2024-05-01 16:50 UTC, StephenFluin commented on src/pages/dev/amplifier/chain-integration/introduction.mdx
> +- This is the gateway contract for your source chain, built using the same tech stack as that chain. It serves as the primary API for developers sending messages from your chain.
"same tech stack as that chain" is not quite right. You use the tech stack of the chain. AKA Ethereum isn't built in Solidity, but the tech stack for smart contracts on Ethereum is Solidity.

2024-05-01 16:50 UTC, StephenFluin commented on src/pages/dev/amplifier/chain-integration/introduction.mdx
> +To connect your chain to the Axelar network via the Interchain Amplifier, you’ll need to build or instantiate four smart contracts and one relayer service. The [chain integration tutorial](/dev/ampli
Any time we say there's an authorization step, we should explain that this is devnet-only, and that the connections in testnet and mainnet will be done via governance of the network.

2024-05-01 16:50 UTC, StephenFluin commented on src/pages/dev/amplifier/chain-integration/introduction.mdx
> +- The contract will have to implement the [Cross-Chain Gateway Protocol](https://github.com/axelarnetwork/cgp-spec).
@milapsheth said that this is outdated and folks should instead implement the API of our EVM gateway.

2024-05-01 17:01 UTC, StephenFluin commented
Is the title of this PR accurate? I'm confused because it's not about contract instantiation?

2024-05-20 13:44 UTC, ffe9f8 commented
Duplicated in current [chain integration intro](https://docs.axelar.dev/dev/amplifier/chain-integration/introduction).

2024-05-20 13:44 UTC, closed without merging