fix: on-chain gas params and un-needed estimator
axelarnetwork/axelar-docs pull request #950
Opened 2024-04-29 11:54 UTC by StephenFluin

improves #949

2024-05-07 18:06 UTC, re1ro requested changes

2024-05-07 18:06 UTC, re1ro commented on public/samples/on-chain-gas-estimate.sol
> +        uint256 estimate = getEstimate(
I think this estimation part is supposed to happen off-chain, not in the contract. We still need to attach the right amount of value to the TX that is equal to estimate.

2024-05-07 18:06 UTC, re1ro commented on public/samples/on-chain-gas-estimate.sol
> +            true, // bool estimateOnChain - was this gas estimated on-chain?
This boolean is to enforce checking supplied value against the estimate performed inside of the gas service. If payment is not enough it will revert

2024-05-07 18:06 UTC, re1ro commented on public/samples/on-chain-gas-estimate.sol
>          uint256 refund = msg.value - estimate;
If we are doing the estimate off-chain this refund should be removed as well.

2024-06-06 20:43 UTC, closed without merging

2024-06-06 20:43 UTC, StephenFluin commented
Fixed in #965