fix: check active worker set
axelarnetwork/axelar-docs pull request #981
Opened 2024-05-23 17:39 UTC by ffe9f8

Preview: https://axelar-docs-git-marty-verifier-active-set-axelar-network.vercel.app/validator/amplifier/verifier-onboarding

2024-06-06 20:47 UTC, StephenFluin requested changes

2024-06-06 20:47 UTC, StephenFluin commented on src/layouts/navigation.ts
> +              title: "Become a Verifier (Worker)",
Just verifier

2024-06-06 20:47 UTC, StephenFluin commented on src/pages/validator/amplifier/verifier-onboarding.mdx
> +axelard q wasm contract-state smart $PROVER_AVALANCHE '"get_verifier_set"' --node $RPC
Where do I get the prover? As a verifier I don't know this. Isn't there a prover for each chain I'm verifying for?

2024-06-06 20:47 UTC, StephenFluin commented on src/pages/validator/amplifier/verifier-onboarding.mdx
> +Active verifier sets are the same as signers unless there is a verifier set update in progress, because the prover requires a few extra steps before active verifier sets can be confirmed as signers.
What extra steps? who?

2024-06-26 15:12 UTC, ffe9f8 commented
Will update in another PR.

2024-06-26 15:12 UTC, closed without merging